snc_redis:
    clients:
        
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
            logging: '%kernel.debug%'
        
        session:
            type: predis
            alias: session
            dsn: "%env(REDIS_URL)%/1"
            logging: '%kernel.debug%'
